service: lambda-uppy
provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-east-2
  Role: ***
  environment:
    AWS_S3_BUCKET: uppy.lambda.demo
    AWS_S3_ACL: public-read
functions:
  app:
    handler: lambda.handler
    events: 
      - http: ANY {proxy+}
        cors: true
      - http: ANY /
        cors: true
